language: csharp
mono: none
dotnet: 2.1.502
solution: Cactus.Blade.Serialization.sln
install:
  - dotnet restore
script:
  - dotnet msbuild /p:Configuration=Release Cactus.Blade.Serialization.sln
  - dotnet restore
  - dotnet test Serialization.Test/Serialization.Test.csproj
