language: csharp
mono: none
dotnet: 2.1.502
solution: Cactus.Blade.MimeType.sln
install:
  - dotnet restore
script:
  - dotnet msbuild /p:Configuration=Release Cactus.Blade.MimeType.sln
  - dotnet restore
  - dotnet test MimeType.Test/MimeType.Test.csproj
